In [1]:
import numpy as np

array = np.array([34, 12, 7, 56, 89, 22, 457])
sorted_array = np.sort(array)

print("Original array:")
print(array)

print("Sorted array:")
print(sorted_array)

Original array:
[ 34  12   7  56  89  22 457]
Sorted array:
[  7  12  22  34  56  89 457]


In [2]:
import numpy as np

a = np.array([[3, 10, 2], [1, 5, 7], [6, 7, 5]])

print(np.sort(a))

array4 = np.sort(a, axis=0)
print(array4)

a1 = np.sort(a, axis=None)
print(a1)

a2 = np.sort(a, axis=1)
print(a2)

[[ 2  3 10]
 [ 1  5  7]
 [ 5  6  7]]
[[ 1  5  2]
 [ 3  7  5]
 [ 6 10  7]]
[ 1  2  3  5  5  6  7  7 10]
[[ 2  3 10]
 [ 1  5  7]
 [ 5  6  7]]


In [5]:
import pandas as pd

l = [1, 2, 3]
s = pd.Series(l)
print(s)
data = {"Name": ["Lowkya", "Keerthana", "bavya"],
        "Age": [19, 18, 21],
        "Study": ["BTECH", "CSE", "EEE"]}

df = pd.DataFrame(data)
print("DataFrame:")
print(df)

0    1
1    2
2    3
dtype: int64
DataFrame:
        Name  Age  Study
0     Lowkya   19  BTECH
1  Keerthana   18    CSE
2      bavya   21    EEE


In [6]:
import heapq

def uniform_cost_search(graph, start, goal):
    priority_queue = [(0, start, [])]
    visited = set()

    while priority_queue:
        cost, node, path = heapq.heappop(priority_queue)
        if node in visited:
            continue

        path = path + [node]
        visited.add(node)

        if node == goal:
            return cost, path

        for neighbour, edge_cost in graph.get(node, []):
            if neighbour not in visited:
                heapq.heappush(priority_queue, (cost + edge_cost, neighbour, path))

graph = {
    'A': [('B', 8), ('C', 3)],
    'B': [('E', 10), ('D', 2)],
    'C': [('F', 6), ('G', 7)],
    'F': [('E', 2), ('G', 1)]
}

start_node = 'A'
goal_node = 'E'

cost, path = uniform_cost_search(graph, start_node, goal_node)
print("Least cost path from", start_node, "to", goal_node, ":", path)
print("Total cost:", cost)

Least cost path from A to E : ['A', 'C', 'F', 'E']
Total cost: 11


In [7]:
import heapq

def astar_search(start, goal, graph, heuristic):
    open_list = [(0, start, [])]
    
    while open_list:
        cost, current_node, path = heapq.heappop(open_list)
        path = path + [current_node]
        
        if current_node == goal:
            return path, cost
        
        for neighbor, edge_cost in graph.get(current_node, []):
            heapq.heappush(open_list, (cost + edge_cost + heuristic[neighbor], neighbor, path))
    
    return None

graph = {
    'A': [('B', 6), ('C', 3)],
    'B': [('D', 2), ('E', 4)],
    'C': [('F', 10)],
    'D': [('G', 4)],
    'E': [('G', 1)],
    'F': [('G', 2)]
}

heuristic = {
    'A': 7, 'B': 6, 'C': 5, 'D': 4, 'E': 3, 'F': 6, 'G': 0
}

start_node = 'A'
goal_node = 'G'

path, total_cost = astar_search(start_node, goal_node, graph, heuristic)

print("Least cost path from", start_node, "to", goal_node, "is", path)
print("Total cost:", total_cost)

Least cost path from A to G is ['A', 'B', 'E', 'G']
Total cost: 20


In [8]:
import random

def objective_function(x):
    return -x**2 + 4*x

def hill_climb(start_x, step_size=0.1, max_iterations=100):
    current_x = start_x
    current_value = objective_function(current_x)
    
    for _ in range(max_iterations):
        neighbours = [current_x + step_size, current_x - step_size]
        best_neighbour = max(neighbours, key=objective_function)
        best_neighbour_value = objective_function(best_neighbour)
        
        if best_neighbour_value > current_value:
            current_x, current_value = best_neighbour, best_neighbour_value
        else:
            break
    
    return current_x, current_value

start_point = random.uniform(-10, 10)
best_x, best_value = hill_climb(start_point)

print(f"Optimal x: {best_x:.4f}")
print(f"Optimal value: {best_value:.4f}")

Optimal x: 1.9988
Optimal value: 4.0000


In [13]:
MAX, MIN = 1000, -1000

def minimax(depth, nodeIndex, maximizingPlayer, values, alpha, beta):
    if depth == 3:
        return values[nodeIndex]
    
    if maximizingPlayer:
        best = MIN
        for i in range(2):
            val = minimax(depth + 1, nodeIndex * 2 + i, False, values, alpha, beta)
            best = max(best, val)
            alpha = max(alpha, best)
            if beta <= alpha:
                break
        return best
    else:
        best = MAX
        for i in range(2):
            val = minimax(depth + 1, nodeIndex * 2 + i, True, values, alpha, beta)
            best = min(best, val)
            beta = min(beta, best)
            if beta <= alpha:
                break
        return best

if __name__ == "__main__":
    values = [3, 5, 6, 9, 1, 2, 0, -1]
    print("The optimal value is:", minimax(0, 0, True, values, MIN, MAX))


The optimal value is: 5


In [15]:
def print_board(board):
    for row in board:
        print(" ".join(row))
    print("\n")

def is_safe(board, row, col, N):
    for i in range(row):
        if board[i][col] == '♛':
            return False
    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if j < 0:
            break
        if board[i][j] == '♛':
            return False
    for i, j in zip(range(row, -1, -1), range(col, N)):
        if j >= N:
            break
        if board[i][j] == '♛':
            return False
    return True

def solve_n_queens_util(board, row, N):
    if row >= N:
        print_board(board)
        return True
    for col in range(N):
        if is_safe(board, row, col, N):
            board[row][col] = '♛'
            if solve_n_queens_util(board, row + 1, N):
                return True
            board[row][col] = '⬜'
    return False

def solve_n_queens(N):
    board = [['⬜' for _ in range(N)] for _ in range(N)]
    if not solve_n_queens_util(board, 0, N):
        print("❌ No solution found!")
    else:
        print("✅ Solution found!")

N = 8  
solve_n_queens(N)


♛ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
⬜ ⬜ ⬜ ⬜ ♛ ⬜ ⬜ ⬜
⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ♛
⬜ ⬜ ⬜ ⬜ ⬜ ♛ ⬜ ⬜
⬜ ⬜ ♛ ⬜ ⬜ ⬜ ⬜ ⬜
⬜ ⬜ ⬜ ⬜ ⬜ ⬜ ♛ ⬜
⬜ ♛ ⬜ ⬜ ⬜ ⬜ ⬜ ⬜
⬜ ⬜ ⬜ ♛ ⬜ ⬜ ⬜ ⬜


✅ Solution found!
